org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.caching=true

minecraft.version=1.21.1
neoforge.version=21.1.243
java.version=21

mod.id=camerapture
mod.group=me.chrr
mod.version=2.0.0-neoforge.4-dev

webp4j.version=2.1.1
clothconfig.version=15.0.140
jade.version=15.8.3
firstpersonmodel.version=2.4.6
